// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "File.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class File
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.04.01
// App/Edition: Files/
// User:        2sic Web-Developer
// When:        2024-03-12 08:23:39Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for File 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// File data. <br/>
  /// Generated 2024-03-12 08:23:39Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Description`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class File: AutoGenerated.ZagFile
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.File in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagFile: Custom.Data.CustomItem
  {
    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _item.String("Description", fallback: "");

    /// <summary>
    /// Icon as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Icon", scrubHtml: true) etc.
    /// </summary>
    public string Icon => _item.String("Icon", fallback: "");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");

    /// <summary>
    /// Url as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Url")
    /// </summary>
    public string Url => _item.Url("Url");

    /// <summary>
    /// Get the file object for Url - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile UrlFile => _item.File("Url");

    /// <summary>
    /// Get the folder object for Url.
    /// </summary>
    public IFolder UrlFolder => _item.Folder("Url");
  }
}