// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Folder.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Folder
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.04.01
// App/Edition: Files/
// User:        2sic Web-Developer
// When:        2024-03-12 08:23:39Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Folder 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Folder data. <br/>
  /// Generated 2024-03-12 08:23:39Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Description`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Folder: AutoGenerated.ZagFolder
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Folder in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagFolder: Custom.Data.CustomItem
  {
    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _item.String("Description", fallback: "");

    /// <summary>
    /// Files as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Files")
    /// </summary>
    public string Files => _item.Url("Files");

    /// <summary>
    /// Get the file object for Files - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile FilesFile => _item.File("Files");

    /// <summary>
    /// Get the folder object for Files.
    /// </summary>
    public IFolder FilesFolder => _item.Folder("Files");

    /// <summary>
    /// HeadingType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HeadingType", scrubHtml: true) etc.
    /// </summary>
    public string HeadingType => _item.String("HeadingType", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public new string Title => _item.String("Title", fallback: "");
  }
}