// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ListHeader.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ListHeader
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataClassesGenerator v17.04.01
// App/Edition: Files/
// User:        2sic Web-Developer
// When:        2024-03-12 08:23:39Z
namespace AppCode.Data
{
  // This is a generated class for ListHeader 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ListHeader data. <br/>
  /// Generated 2024-03-12 08:23:39Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.HeadingType`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ListHeader: AutoGenerated.ZagListHeader
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ListHeader in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagListHeader: Custom.Data.CustomItem
  {
    /// <summary>
    /// HeadingType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HeadingType", scrubHtml: true) etc.
    /// </summary>
    public string HeadingType => _item.String("HeadingType", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public new string Title => _item.String("Title", fallback: "");
  }
}